#!/bin/zsh

if [[ -z "$1" ]]
then
    echo "Usage: ss-video <video-file> [output-name]"

elif [ -z "$2"]; then
    ffmpeg -ss 00:00:01 -i $1 -frames:v 1 -q:v 2 screenshot.png
else
    ffmpeg -ss 00:00:01 -i $1 -frames:v 1 -q:v 2 $2
fi
